# Generated by Django 3.2.4 on 2021-06-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_tasks', to='testing.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_tasks', to='testing.task')),
            ],
        ),
    ]
