# Generated by Django 3.2.4 on 2021-06-04 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_takentask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='student',
        ),
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='StudentSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='testing.solution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to='testing.student')),
            ],
        ),
    ]
