# Generated by Django 3.2.4 on 2021-06-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20210605_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.FileField(upload_to='test_files/', verbose_name='Вихідні дані'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Назва:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
