# Generated by Django 3.2.4 on 2021-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20210605_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Короткий опис')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files_uploaded/material_files/', verbose_name='Додаток')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='input_file',
            field=models.FileField(upload_to='files_uploaded/test_files/', verbose_name='Вхідні дані'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.FileField(upload_to='files_uploaded/test_files/', verbose_name='Вихідні дані'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
