# Generated by Django 3.2.4 on 2021-06-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20210605_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input_file',
            field=models.FileField(upload_to='files_uploaded/test_files', verbose_name='Вхідні дані'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.FileField(upload_to='files_uploaded/test_files', verbose_name='Вихідні дані'),
        ),
    ]
